name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USER }}
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "${SSH_KEY}" > key.pem
        chmod 600 key.pem
        scp -i "key.pem" -r ./dist $USERNAME@$HOST:/var/www/html/react-ec2
        ssh -i "key.pem" $USERNAME@$HOST "sudo systemctl restart nginx"
